//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowAccount.Roslyn.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FlowAccount.Roslyn.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FAWRN0001Title {
            get {
                return ResourceManager.GetString("FAWRN0001Title", resourceCulture);
            }
        }
        
        internal static string FAWRN0001MessageFormat {
            get {
                return ResourceManager.GetString("FAWRN0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string FAWRN0001Category {
            get {
                return ResourceManager.GetString("FAWRN0001Category", resourceCulture);
            }
        }
        
        internal static string FAWRN0001Description {
            get {
                return ResourceManager.GetString("FAWRN0001Description", resourceCulture);
            }
        }
        
        internal static string FAWRN0001Link {
            get {
                return ResourceManager.GetString("FAWRN0001Link", resourceCulture);
            }
        }
        
        internal static string FAINF0001Category {
            get {
                return ResourceManager.GetString("FAINF0001Category", resourceCulture);
            }
        }
        
        internal static string FAINF0001Title {
            get {
                return ResourceManager.GetString("FAINF0001Title", resourceCulture);
            }
        }
        
        internal static string FAINF0001MessageFormat {
            get {
                return ResourceManager.GetString("FAINF0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string FAINF0001Description {
            get {
                return ResourceManager.GetString("FAINF0001Description", resourceCulture);
            }
        }
        
        internal static string FAINF0001Link {
            get {
                return ResourceManager.GetString("FAINF0001Link", resourceCulture);
            }
        }
        
        internal static string FAINF0002Title {
            get {
                return ResourceManager.GetString("FAINF0002Title", resourceCulture);
            }
        }
        
        internal static string FAINF0002Category {
            get {
                return ResourceManager.GetString("FAINF0002Category", resourceCulture);
            }
        }
        
        internal static string FAINF0002Description {
            get {
                return ResourceManager.GetString("FAINF0002Description", resourceCulture);
            }
        }
        
        internal static string FAINF0002MessageFormat {
            get {
                return ResourceManager.GetString("FAINF0002MessageFormat", resourceCulture);
            }
        }
        
        internal static string FAINF0002Link {
            get {
                return ResourceManager.GetString("FAINF0002Link", resourceCulture);
            }
        }
    }
}
